### ISSUE TITLE
Trouble seeing on dark themes

### ISSUE THREAD

**Issue by pomutemu** [mark-hahn/search-all-keybindings#3]
On Atom Light theme:
[![Gyazo](http://i.gyazo.com/f8ab6a50ce3e3066b56c331e3292719e.png)](http://gyazo.com/f8ab6a50ce3e3066b56c331e3292719e)

On Atom Dark theme:
[![Gyazo](http://i.gyazo.com/a9f6d5871e4661a61929a2aa1be70433.png)](http://gyazo.com/a9f6d5871e4661a61929a2aa1be70433)

**Comment by mark-hahn** [comment]
I will fix this today.
