### ISSUE TITLE
"Loaded 0 bindings" on Atom 0.211.0

### ISSUE THREAD

**Issue by pomutemu** [mark-hahn/search-all-keybindings#6]
[![Gyazo](http://i.gyazo.com/93ecb82638707ccf8d4f3271421cc466.png)](http://gyazo.com/93ecb82638707ccf8d4f3271421cc466)

search-all-keybindings@0.1.5

**Comment by mark-hahn** [comment]
I just want everyone to know I haven't forgotten about the issues.  I've just been too busy.  I'll get to them by this weekend.
